language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt -r requirements-dev.txt"

# command to run tests
script:
  - mkdir ~/books
  - cd ui
  - python -m unittest discover
  - flake8 *.py
