language: python

python:
  - "3.5"
  - "3.6"

rust:
  - "1.34.2"

install: "pip3 install -r requirements.txt"

script:
  - rustc --version
  - cargo --version
  - ./test
  - ./lint
  - mkdir ~/canute-media && cp -r books ~/canute-media/sd-card && cp config.rc.travis config.rc
  - ./canute_ui --fuzz 550
