language: python
python:
  - "3.5"
  - "3.6"

install: "pip3 install -r requirements.txt"

script:
  - ./test
  - ./lint
  - mkdir ~/books && cp -r books ~/books/sd-card && cp config.rc.travis config.rc
  - ./canute_ui --fuzz 550
