language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip3 install -r requirements.txt
  - wget https://github.com/Bristol-Braille/canute-ui-rust/releases/latest/download/libbookindex.so

script:
  - LD_LIBRARY_PATH=. ./test
  - ./lint
  - mkdir ~/canute-media && cp -r books ~/canute-media/sd-card && cp config.rc.travis config.rc
  - LD_LIBRARY_PATH=. ./canute_ui --fuzz 550
