language: python
python:
  - "3.5"
  - "3.6"

install: "pip3 install -r requirements.txt"

script:
  - ./test
  - flake8 --version
  - ./lint
  - mkdir ~/canute-media && cp -r books ~/canute-media/sd-card && cp config.rc.travis config.rc
  - ./canute_ui --fuzz 30
