language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install: "pip3 install -r requirements.txt"

script:
  - ./test
  - ./lint
  - cp -r books ~/ && cp config.rc.travis config.rc
  - ./canute_ui --fuzz 550
