#!/usr/bin/env bash
flake8 --filename='./canute_ui,*.py' \
    --exclude='doc,ui/driver/qt/main_window.py,ve*' \
    --max-line-length=100 \
    --builtins="_" \
    --multiline-quotes="'" && echo 'Lint OK'
