rotor:
    inputToPosition:
        0: 5
        1: 1
        2: 7
        3: 0
        4: 6
        5: 8
        6: 9
        7: 10
    numberOfPositions: 11

display:
    rows: 1
    columns: 8

rotorStepper:
    steps: 400

input:
    maxInt: 7
