name: Build Canute UI book indexer
on:
  push:
    branches:
      - main
      - 285-rust-cross-compilation
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build docker image
      run: docker build -t bristol-braille/bookindex:latest .
    - name: Build library
      run: |
        docker run -t -e "HOME=/work" -w /work -v "$PWD:/work" bristol-braille/bookindex:latest
        ls -l .
        ls -l target/arm-unknown-linux-gnueabihf/release/
        mv target/arm-unknown-linux-gnueabihf/release/libbookindex.so .
    - name: Make tarball
      run: tar czvf canute-ui.tar.gz README.md LICENSE requirements-pi.txt canute_ui ui libbookindex.so config.rc.in run.sh books
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: canute-ui.tar.gz
