name: Build Canute UI book indexer
on:
  push:
    branches:
      - main
      - 285-rust-cross-compilation
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build docker images
      run: docker build -t bristol-braille/bookindex:latest Dockerfile
    - name: Run tests
      run: docker run -t -e "HOME=/work" -w /work -v "$PWD:/work" bristol-braille/bookindex:latest
